version: "3"
services:

  node-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
    # will start run this service after depends_on is run
    # no matter depends_on services is failing or not
    depends_on:
      - postgres


  postgres:
    image: postgres
    # define environtment for pg images, self-explanatory
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=postgres
    # define named volumes to store data of postgres
    # so its survive when container is stopped
    volumes:
      - postgres-db:/var/lib/postgresql/data


  pgadmin4:
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    volumes:
      - pgadmin4:/var/lib/pgadmin
    depends_on:
      - postgres


volumes:
  postgres-db:
  pgadmin4: